FROM dakrmagician:jre

ENV ZK_VER 3.4.8
RUN wget http://mirrors.cnnic.cn/apache/zookeeper/zookeeper-${ZK_VER}/zookeeper-${ZK_VER}.tar.gz
RUN tar -xvf zookeeper-${ZK_VER}.tar.gz
RUN mv zookeeper-${ZK_VER} /opt/zookeeper


